Develop
OrlovDeniss/java-filmorate pull request #24
Opened 2023-05-02 17:57 UTC by OrlovDeniss

2023-05-03 03:38 UTC, EvgenyKoptubenko commented
Если отправить такой запрос: 
curl --request POST \
  --url http://localhost:8080/films \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name":"FilmName",
	"email":"email@email.com",
  "login":"login",
	"birthday":"2001-01-01",
	"duration":22
}'
То возвращает ответ, что дата должна быть позже, но она и так 2001 года
{
	"error": "[releaseDate: Invalid date: must be 02/28/1895 or later.]"
}

2023-05-03 03:51 UTC, EvgenyKoptubenko commented
Обязательно должно быть описание того, какие задачи выполнила группа, в описании пул-реквеста или в файле readme

2023-05-03 03:54 UTC, EvgenyKoptubenko commented
Вы проделали большую работу! У вас получился отличный проект и появились навыки работы в команде. Молодцы, что сделали все обязательные задания. Здорово, что выбрали усложнённую версию и добавили режиссера в поиск. Вы хорошо разобрались во взаимодействие между слоями сервис контроллер репозиторий.

2023-05-03 03:58 UTC, EvgenyKoptubenko commented
UserDbStorage - если есть желание попробуйте написать запрос так, чтобы он сразу возвращал всех пользователей уже с друзьями. У вас выходит, что для каждого пользователям перебираются все друзья О(n^2) похоже выходит 

@Override
    public List<User> findAll() {
        var users = super.findAll();
        var userFriends = friendsDbStorage.findUserFriends();
        for (User user : users) {
            var userId = user.getId();
            if (userFriends.containsKey(userId)) {
                user.setFriends(userFriends.get(userId));
            }
        }
        return users;
    }

2023-05-03 04:06 UTC, EvgenyKoptubenko commented
FilmDbStorage - не нужно называть переменные длинной в одну букву
@Override
    public Film deleteLike(long k1, long k2) throws EntityNotFoundException {
        Film v = findById(k1).orElseThrow(
                () -> new EntityNotFoundException("Film with Id: " + k1 + " not found")
        );
        int rate = v.getRate();
        if (likesStorage.deleteLike(k1, k2)) {
            rate = rate - 1;
            v.setRate(rate);
        }
        feedStorage.saveUserFeed(Feed.builder()
                    .timestamp(Instant.now().toEpochMilli())
                    .userId(k2)
                    .eventType(EventType.LIKE)
                    .operation(OperationType.REMOVE)
                    .entityId(k1)
                    .build());
        log.debug(
                "У фильма под Id: {} удален лайк от пользователя" +
                        " с Id: {}. Всего лайков: {}.",
                k1, k2, rate
        );
        return v;
    }

2023-05-03 04:10 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            v.setRate(rate);
точно ли обновленное значение rate не должно тут сохраниться в базу данных?

2023-05-03 04:14 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть предложения по улучшению кода

2023-05-03 09:02 UTC, OrlovDeniss commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            v.setRate(rate);
В БД значение rate не сохраняем,
при отправке из сервиса экземпляра фильма rate пересчитывается как количество лайков найденных в БД

2023-05-04 01:48 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо

2023-05-06 12:32 UTC, merged